set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"

bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-H previous-window
bind -n M-L next-window

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n S-Left  previous-window
bind -n S-Right next-window

set -g @tokyo-night-tmux_theme 'night'   # night / storm / day

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fabioluciano/tokyo-night-tmux'

run '~/.tmux/plugins/tpm/tpm'

set-window-option -g mode-keys vi

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
